# Generated by Django 5.0.2 on 2024-03-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_repairrequest_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logs', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
