# Generated by Django 5.0.2 on 2024-03-12 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_department_id_alter_equipmenttype_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
