# Generated by Django 5.0.2 on 2024-03-12 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
