# Generated by Django 5.0.2 on 2024-03-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_kindofequipment_alter_repairrequest_equip_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlogs',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
